debug = false
disable_crowdin = false
check_for_updates = true

[activations.4aec07ba-d109-3345-9a0a-92022a116cd0]
toggle = false
type = "VOICE"
[[key_bindings]]
keys = []
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings]]
keys = []
name = "key.plasmovoice.general.action"
any_context = false
category = "key.plasmovoice.general"

[servers.2a377759-577c-49c0-8d4c-ef5412296ab0.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32

[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 1.0
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = true

[voice]
disabled = false
microphone_disabled = false
activation_threshold = -48.0
input_device = ""
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false

[voice.volumes.source_30f9dbb2-fe22-4e59-8b41-d9111b9b2177]
volume = 1.0
[voice.volumes.proximity]
volume = 2.0
[voice.volumes.source_306264b4-59bb-4f3c-a64f-c8373b846889]
volume = 1.0
[voice.volumes.source_1147deac-784e-4cf0-a64e-147d25bb8d11]
volume = 1.0
[voice.volumes.source_8a686fd6-50cc-4e5b-95a0-7672bff89e3d]
volume = 2.0
[voice.volumes.source_1f29eecf-4244-4164-901d-a8d02b290e87]
volume = 1.0
[voice.volumes.source_f6c99581-c3bd-4277-82d5-72718bcf0882]
volume = 1.0
[voice.volumes.source_64d95f29-22cc-450f-896d-e334cdb4da04]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 1
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_RIGHT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "ON"
