#Whether to allow patting players with a shift-right-click.
allowPats = false
#Whether to load contributor info from the internet.
#If false, no one will appear as a contributor.
loadContributors = false

